#!/usr/bin/env bash

# Number of docker containers
count=$(docker ps -aq | wc -l)
# Recent docker container IP
#recent_ip=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" $(docker ps -ql))
#echo "$LABEL$count: $recent_ip"
echo "$LABEL$count"
